services:
  maria:
    container_name: db
    image: mariadb
    env_file: ".env"
    ports:
      - 3306:3306
    volumes:
      - maria:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MARIADB_PASSWORD",
        ]
      timeout: 1s
      retries: 10
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  nodejs:
    container_name: backend
    build: "./"
    env_file: ".env"
    ports:
      - 4000:4000
    volumes:
      - maria:/app
    restart: always
    depends_on:
      redis:
        condition: service_started
      maria:  
        condition: service_healthy
volumes:
  maria:
    external: true
