services:
  maria:
    container_name: db
    image: mariadb
    env_file: ".env"
    ports:
      - 3306:3306
    volumes:
      - maria:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MARIADB_PASSWORD",
        ]
      timeout: 1s
      interval: 1s
      retries: 3
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  nodejs:
    container_name: backend
    image: wildsoft/playgrounddev:latest
    build: "./"
    env_file: ".env"
    ports:
      - 80:80
    restart: always
    depends_on:
      redis:
        condition: service_started
      maria:
        condition: service_healthy
volumes:
  maria:
    external: true