const CODE = {
  SUCCESS: 200,

  // ACCOUNT
  ACCOUNT_NOT_REGISTERED: 210,
  ACCOUNT_NICKNAME_DUPLICATED: 211,
  ACCOUNT_WAITING: 212,

  // SESSION
  SESSION_EXPIRED: 213,

  // FRIEND STATUS
  FRIEND_CANCELED: 214,

  // FRIEND
  FRIEND_PENDING: 0,
  FRIEND_ACCEPTED: 1,
  FRIEND_BLOCKED: 2,

  // NOTIFICATION
  NOTIFICATION_FRIEND: 0,
  NOTIFICATION_FRIEND_ACCEPTED: 1,
};

export default CODE;
